# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [7]:
planet = "Earth"
diameter = 12742
O="The diameter of {} is {} kilometers".format("Earth",12742)
O

'The diameter of Earth is 12742 kilometers'

## 3. In this nest dictionary grab the word "hello"

In [17]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
p=(d["k1"][3]["tricky"][3]["target"][3])
p

'hello'

# Numpy

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [21]:
import numpy as np
array=np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
import numpy as np
array=np.ones(10)*5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [28]:

array=np.arange(20,35,2)
array

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [29]:
array=np.arange(9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=a+b
c

array([5, 7, 9])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [33]:
import pandas as pd
d=pd.DataFrame(np.arange(6).reshape(3,2))
d.columns=['1','2']
d.index=['a','b','c']
d

   1  2
a  0  1
b  2  3
c  4  5

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [34]:
S=pd.date_range(start="2023-01-01",end="2023-02-10")
S

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [35]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
pd.DataFrame(lists)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24